name: Test

on: [push, pull_request]

jobs:
  build:
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        os: [macos-latest,macos-12, macos-11, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Test
      run: swift test -v
