name: Test

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, ubuntu-latest, windows-latest]
        swift: ["5.7", "5.8", "5.9"]
    runs-on: ${{ matrix.os }}

    steps:
    - if: ${{ (runner.os != 'Windows') && (matrix.swift != '5.7') }}
      name: Setup Swift Version
      uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: ${{ matrix.swift }}

    - if: ${{ (runner.os == 'Windows') && (matrix.swift == '5.7') }}
      name: Setup Swift (5.7 on Windows) Version
      uses: compnerd/gha-setup-swift@main
      with:
        branch: swift-5.7-release
        tag: 5.7-RELEASE

    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build
      run: swift build
      
    - name: Test
      run: swift test

