name: Build & Test

on: [push]

jobs:
  
  build-xcode:
    strategy:
      fail-fast: false
      matrix:
       os: [macos-14, macos-15]
       destination: ["platform=macOS,name=My Mac", "platform=iOS Simulator,name=iPhone 16 Pro", "platform=tvOS Simulator,name=Apple TV 4K (3rd generation)", "platform=watchOS Simulator,name=Apple Watch Series 10 (42mm)", "platform=visionOS Simulator,name=Apple Vision Pro"]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.2.app

    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Test
      run: xcodebuild -scheme Relax-Package -destination '${{ matrix.destination }}' test

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, ubuntu-latest]
        swift: ["5.10", "6.0.3"]
    runs-on: ${{ matrix.os }}

    steps:
    - if: ${{ (runner.os == 'Windows') }}
      name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      
    - name: Setup Swift Version
      uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: ${{ matrix.swift }}

    - name: Get Swift Version
      run: swift --version

    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build
      run: swift build
      
    - name: Test
      run: swift test

