name: Test

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, ubuntu-latest, windows-latest]
	swift: ["5.7", "5.8", "5.9"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: ${{ matrix.swift }}

    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build
      run: swift build
      
    - name: Test
      run: swift test

