name: Test

on: [push]

jobs:
  build:
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        os: [macos-13, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - if: runner.os == 'Windows'
      name: Setup Swift
      uses: compnerd/gha-setup-swift@main
      with:
        branch: swift-5.9.2-release
        tag: 5.9.2-RELEASE

    - if: runner.name == 'macos-13'
      run: 'sudo xcode-select -s /Applications/Xcode_15.1.app'
        
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Build
      run: swift build
      
    - name: Test
      run: swift test
