name: Test

on: [push]

jobs:
  build:
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        os: [macos-13, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.9.2"
      
    - name: Build
      run: swift build
      
    - name: Test
      run: swift test
