name: Test

on: [push]

jobs:
  build:
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        os: [macos-13, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    
    - if: runner.os == 'Windows'
      name: Setup Swift
      uses: compnerd/gha-setup-swift@main
      with:
        branch: swift-5.9.2-release
        tag: 5.9.2-RELEASE

    - if: runner.os != 'Windows'
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.9"

    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build
      run: swift build
      
    - name: Test
      run: swift test
