name: Test

on: [push, pull_request]

jobs:
  build:
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        os: [macos-12, macos-13, macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - if: runner.os == 'Windows'
      name: Setup Swift
      uses: compnerd/gha-setup-swift@main
      with:
        branch: swift-5.7-release
        tag: 5.7-RELEASE
        
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Build
      run: swift build
      
    - name: Test
      run: swift test
